import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  es: {
    gym: "Gym",
    nutrition: "Nutrición",
    community: "Comunidad",
    stats: "Estadísticas",
    profile: "Perfil",
    train: "Entrenar",
    explore: "Explorar",
    history: "Historial",
    new_routine: "NUEVA RUTINA",
    new_folder: "NUEVA CARPETA",
    my_routines: "MIS RUTINAS",
    active_session: "Sesión Actual",
    finish_workout: "TERMINAR ENTRENAMIENTO",
    add_exercise: "Añadir ejercicio",
    search_placeholder: "¿Qué entrenamos hoy?",
    physical_config: "Configuración Física",
    age: "EDAD",
    weight: "PESO (KG)",
    height: "ALTURA (CM)",
    language: "IDIOMA",
    save: "GUARDAR",
    feedback_title: "Envíanos tus comentarios",
    feedback_placeholder: "¿Cómo podemos mejorar Vórtice?",
    send_feedback: "ENVIAR COMENTARIOS",
    logout: "Cerrar Sesión",
    level: "NIVEL",
    intensity: "INTENSIDAD ACTUAL",
    routines: "Rutinas",
    save_routine: "Guardar rutina",
    saving: "Guardando...",
    routine_name_placeholder: "Nombre de la rutina",
    no_folder: "Sin carpeta",
    folder_name_placeholder: "Nombre de la carpeta",
    start_workout: "INICIAR ENTRENAMIENTO",
    no_exercises_yet: "Sin ejercicios aún",
    tap_to_add: "Tocá el botón de abajo para agregar",
    exercises: "EJERCICIOS",
    series: "SERIES",
    duration: "DURACIÓN",
    estimated_duration: "DURACIÓN ESTIMADA",
    muscle_summary: "Resumen muscular",
    muscles_worked: "MÚSCULOS TRABAJADOS",
    set: "serie",
    sets: "series",
    muscle_map: "MAPA MUSCULAR",
    last_7_days: "ÚLTIMOS 7 DÍAS",
    low: "Bajo",
    medium: "Medio",
    high: "Alto",
    delete: "Eliminar",
    edit: "Editar",
    share: "Compartir",
    clone: "Clonar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    loading: "Cargando...",
    install_title: "Instalá la app",
    install_subtitle: "Mejor experiencia, acceso directo",
  },
  en: {
    gym: "Gym",
    nutrition: "Nutrition",
    community: "Community",
    stats: "Stats",
    profile: "Profile",
    train: "Train",
    explore: "Explore",
    history: "History",
    new_routine: "NEW ROUTINE",
    new_folder: "NEW FOLDER",
    my_routines: "MY ROUTINES",
    active_session: "Active Session",
    finish_workout: "FINISH WORKOUT",
    add_exercise: "Add exercise",
    search_placeholder: "What are we training today?",
    physical_config: "Physical Stats",
    age: "AGE",
    weight: "WEIGHT (KG)",
    height: "HEIGHT (CM)",
    language: "LANGUAGE",
    save: "SAVE",
    feedback_title: "Send us your feedback",
    feedback_placeholder: "How can we improve Vórtice?",
    send_feedback: "SEND FEEDBACK",
    logout: "Log Out",
    level: "LEVEL",
    intensity: "CURRENT INTENSITY",
    routines: "Routines",
    save_routine: "Save routine",
    saving: "Saving...",
    routine_name_placeholder: "Routine name",
    no_folder: "No folder",
    folder_name_placeholder: "Folder name",
    start_workout: "START WORKOUT",
    no_exercises_yet: "No exercises yet",
    tap_to_add: "Tap the button below to add",
    exercises: "EXERCISES",
    series: "SETS",
    duration: "DURATION",
    estimated_duration: "ESTIMATED DURATION",
    muscle_summary: "Muscle summary",
    muscles_worked: "MUSCLES WORKED",
    set: "set",
    sets: "sets",
    muscle_map: "MUSCLE MAP",
    last_7_days: "LAST 7 DAYS",
    low: "Low",
    medium: "Med",
    high: "High",
    delete: "Delete",
    edit: "Edit",
    share: "Share",
    clone: "Clone",
    cancel: "Cancel",
    confirm: "Confirm",
    loading: "Loading...",
    install_title: "Install the app",
    install_subtitle: "Better experience, direct access",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('vortice_lang') || 'es');

  useEffect(() => {
    localStorage.setItem('vortice_lang', lang);
  }, [lang]);

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
